### ISSUE TITLE
Dockerfile does not run

### ISSUE THREAD

**Issue by ScubaDrew** [vyshane/cassandra-kubernetes#4]
When I create my own docker image using your Dockerfile, I get an error:

docker: Error response from daemon: Container command '/custom-entrypoint.sh' could not be invoked.

But when I pull your image, vyshane/cassandra:latest it runs fine.

Are you doing something else to make it work?

Thanks!

**Comment by vyshane** [comment]
Is the file custom-entrypoint.sh executable?

**Comment by ScubaDrew** [comment]
Thanks Vy-Shane Xie - that fixed it.
